#!/bin/bash
if [-z "$PYFILE"]; then
echo "ERROR: The pyfile environment variable is not set."
exit 1
fi

if [! -f "$PYFILE"]; then
echo "ERROR: The specified python file '$PYFILE' does not exist."
exit 1
fi

python3 "$PYFILE"
